server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/withSeller;MODE=PostgreSQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
